version: "2"
services:
  server:
    container_name: NODEJS_SERVER
    build: '.'
    volumes: 
      - ./:/node-express-mongo-app
      - ./node_modules:/node_modules
    environment: 
      NODE_ENV: development
    depends_on: 
      - mongo
    links: 
      - mongo
    ports: 
      - "8080:8080"
  
  mongo:
    image: 'mongo'
    container_name: MONGODB
    ports: 
      - "27017:27017"
    volumes: 
      - ./data/mongo:/data/mongo